### ISSUE TITLE
GDPR Consent - PNLiteUserConsentRequestDelegate : Request failed

### ISSUE THREAD

**Issue by Alexi-Pourret** [pubnative/pubnative-hybid-ios-sdk#98] opened 2018-11-07 11:00 UTC
Hi,
My app do have users inside EU and I want to ask their consent before collecting their datas to be fully GDPR compliant.

Following your doc, I am calling `HyBidUserDataManager.sharedInstance().loadConsentPage` but when I tap the "Yes, I agree" button, I have this error :

`PNLiteUserConsentRequestDelegate: Request failed with error: The data couldn’t be read because it isn’t in the correct format.`

Therefore, I can't collect user's data because
`HyBidUserDataManager.sharedInstance().shouldAskConsent()` is always `true`
`HyBidUserDataManager.sharedInstance().canCollectData()` is always `false`

Same happens when using explicitly `HyBidUserDataManager.sharedInstance()?.grantConsent()` , it actually does not change the consent of the user (but does not show the error).

**Comment by eros902002** [comment] 2018-11-07 11:12
Hi @Alexi-Pourret . We're trying but can't reproduce the issue. Are you initialising the SDK properly on the AppDelegate? It needs the app token to be set to authenticate the request. 

We tried removing the initialisation and we get the same error as you. Please could you try initialising the SDK before using the consent management part.

You can find the steps here to initialise the SDK:

https://github.com/pubnative/pubnative-hybid-ios-sdk/wiki/Setup-HyBid#initialise-sdk

Then here you can find thew rest of steps for GDPR:
https://github.com/pubnative/pubnative-hybid-ios-sdk/wiki/GDPR#initialization-overview

Please let us know if you continue having issues.

Best regards

**Comment by Alexi-Pourret** [comment] 2018-11-07 12:36
Indeed, my `HyBid.initWithAppToken` completion is `false`. I checked multiple times my App Auth Token from the Dashboard, which is the good one because I can request and display ads successfully with this token.

**Comment by eros902002** [comment] 2018-11-07 12:59
@Alexi-Pourret From which country are you making this tests. We could use a VPN to check. The issue seems to be that the service that determines if you're on GDPR zone or not is not working for you. That's the only reason why the completion would be false.

Maybe we can test from your geolocation with VPN or something 'cause it's working fine for us.

**Comment by Alexi-Pourret** [comment] 2018-11-07 13:00
I am making tests from France.

**Comment by eros902002** [comment] 2018-11-07 13:12
![screenshot 2018-11-07 at 14 10 53](https://user-images.githubusercontent.com/2706686/48133432-0b295f80-e297-11e8-921c-5e2652730e42.png)

We did tests from France with a VPN and we get successful responses. Are you using a proxy or something to test?

**Comment by Alexi-Pourret** [comment] 2018-11-07 14:10
No, I am not using any proxy or similar technology.

**Comment by eros902002** [comment] 2018-11-08 13:03
Hi @Alexi-Pourret . Could you do any more tests? Based on what you provided we've tested everything and is working fine for us and our partners.

**Comment by jmaire** [comment] 2018-11-08 13:22
Hello,
I have exactly the same problem. So I went deep inside HyBid source code to understand where it comes from.

Whenever I call the `HyBid.initWithAppToken()`, as @eros902002 said, there is a first step that check if you are on GDPR zone or not. This part works well for me.
But then, if you are effectively on GDPR zone, it checks automatically if the current user has given is consent. And the failure starts from this point.

**Comment by jmaire** [comment] 2018-11-08 13:35
So I kept digging.
HyBid send this request to check the consent:

`https://backend.pubnative.net/consent/v1?did=<my-id>`

But whenever HyBid try to process the data received from this request, there is a parse error.

**Comment by eros902002** [comment] 2018-11-08 13:43
Could you see what the API is responding to you @jmaire ? Like in plain text?

**Comment by jmaire** [comment] 2018-11-08 13:56
I receive a response, but the data seems empty.

**Comment by eros902002** [comment] 2018-11-08 14:05
We have been testing this but the response is only empty is the app token is not valid. We've tried playing with every other param but it's only empty with invalid token.

**Comment by jmaire** [comment] 2018-11-08 14:23
Well, I copy and paste the `App auth token` field in my iOS app, from my PubNative project page.

Can a wrong entry in the field `AppStore App ID`cause this problem ?

**Comment by eros902002** [comment] 2018-11-08 14:38
Probably not. Shouldn't be an issue.

**Comment by jmaire** [comment] 2018-11-08 14:47
Since I can request/receive ads and track them on the report tab in my PubNative dashboard, I believe my app token is correct.

Also the app token is not specified in the consent request. The only parameter is the advertising ID. So I believe the problem come from somewhere else.

**Comment by jmaire** [comment] 2018-11-08 15:15
Oh, I didn't notice that there was a header with the app token in the request. Whenever I print the raw data of the response, It says "<0a>".

**Comment by jmaire** [comment] 2018-11-09 10:57
Up!
Do you have any ideas @eros902002 ?

The status code (401) of the response should give you a clue about this problem.

**Comment by eros902002** [comment] 2018-11-09 11:09
@jmaire Is there any way we can test with your app token. Could you PM it to us or maybe tell us which app it is on our dashboard so we can test find it and test. Because it's very weird what's happening and we can't reproduce it.

**Comment by jmaire** [comment] 2018-11-09 11:16
Sure!
How can I contact you privately ?

**Comment by eros902002** [comment] 2018-11-09 11:17
You can do it via mail: eros.ponte@pubnative.net

**Comment by eros902002** [comment] 2018-11-09 11:36
Didn't receive it yet. Will wait a bit

**Comment by jmaire** [comment] 2018-11-09 12:46
Did you receive it ?

**Comment by eros902002** [comment] 2018-11-09 12:47
Yes. Just received it. Let us do some tests

**Comment by eros902002** [comment] 2018-11-09 12:49
@jmaire We tried with your app token in Postman and we do get 401. But with our app token it works. Are you in contact with any of our account managers that gave you the app token? Maybe they need to enable something in your account or something like that. We'll ask them directly but anyway you should go through them.

**Comment by eros902002** [comment] 2018-11-09 13:06
So @jmaire @Alexi-Pourret our account managers will get in contact with you because they need to set up your account for it. Since it's not a code related problem, we'll close the issue if it's ok with you.

**Closed** 2018-11-09 13:36 UTC
